package com.snafx.TripDiary.models;

public enum Activity {
    RUNNING, CYCLING, HIKING, TREKKING, MOUNTAIN_BIKING, SKIING, GYM, SWIMMING, CLIMBING, SNOWBOARDING, FOOTBALL, TENNIS,
    BASKETBALL, BASEBALL, VOLLEYBALL, SQUASH, BOWLING, OTHER
}
